# Generated by Django 5.1.7 on 2025-03-24 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('desc', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('year_of_publication', models.IntegerField()),
                ('isbn', models.CharField(max_length=12)),
            ],
        ),
    ]
